### ISSUE TITLE
Some highlighting remains on the screen while cycling through the notes on a verse

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/create-app#99]
This appears to be related to font sizing. If I make the font small enough, the "underline" highlighting disappears.
https://images.zenhubusercontent.com/310359593/e01c386b-6b1e-44b7-974d-4101304a3896/create_2_0_issue_98.mp4

**Comment by birchamp** [comment]
@cckozie could this have to do with the new highlighted being off the screen?  If so then this is desired/expected behavior when the card is only showing the whitespace above a line of text. 

https://images.zenhubusercontent.com/310359593/236a8998-903a-408f-abb8-d7ce0987a061/screencast_2021_03_23_11_35_16.mp4

**Comment by cckozie** [comment]
Yes, it is related to the highlighted text being partially off of the screen. Closing this issue and adding one to always display a scroll bar if one is needed to help clue users to the fact that the text scrolling is available.
